### ISSUE TITLE
Trouble for harvesting

### ISSUE THREAD

**Issue by MohamedCissoko** [Daniel-KM/OaiPmhGateway#1]
Hello Daniel, 
I'm exploring Omeka, i haven't been  knowing it  before.
I'm trying to setup an OAI-PMH repository for to be harvested.

When i try to test  the OAI-PMH Static Repositories :
-> Check Gateway, I get a red "Checked error" but when I click,  nothing happens.
Or :
-> Harvest, I get "ERR (3): exception 'Omeka_Validate_Exception' with message 'Metadata Prefix: 'doc' was not found in the haystack' in C:\wamp\www\ori-oai\omeka-2.5\application\libraries\Omeka\Record\AbstractRecord.php:535"

I'm working on  localhost (windows 10 / wampserver)

If any information could help.
This is the full error : 

exception 'Omeka_Validate_Exception' with message 'Metadata Prefix: 'doc' was not found in the haystack' in C:\wamp\www\ori-oai\omeka-2.5\application\libraries\Omeka\Record\AbstractRecord.php:536
Stack trace:
#0 C:\wamp\www\ori-oai\omeka-2.5\plugins\OaiPmhGateway\models\OaiPmhGateway.php(263): Omeka_Record_AbstractRecord->save()
#1 C:\wamp\www\ori-oai\omeka-2.5\plugins\OaiPmhStaticRepository\controllers\IndexController.php(318): OaiPmhGateway->harvest('doc', Array)
#2 C:\wamp\www\ori-oai\omeka-2.5\application\libraries\Zend\Controller\Action.php(516): OaiPmhStaticRepository_IndexController->harvestAction()
#3 C:\wamp\www\ori-oai\omeka-2.5\application\libraries\Zend\Controller\Dispatcher\Standard.php(308): Zend_Controller_Action->dispatch('harvestAction')
#4 C:\wamp\www\ori-oai\omeka-2.5\application\libraries\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#5 C:\wamp\www\ori-oai\omeka-2.5\application\libraries\Zend\Application\Bootstrap\Bootstrap.php(105): Zend_Controller_Front->dispatch()
#6 C:\wamp\www\ori-oai\omeka-2.5\application\libraries\Zend\Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#7 C:\wamp\www\ori-oai\omeka-2.5\application\libraries\Omeka\Application.php(77): Zend_Application->run()
#8 C:\wamp\www\ori-oai\omeka-2.5\admin\index.php(28): Omeka_Application->run()
#9 {main}

Regards

**Comment by Daniel-KM** [comment]
Hi,

It seems that the plugin [Archive Document](https://github.com/daniel-km/archivedocument) is missing.

Anyway, for your aim, it's simpler to use OAI-PMH Repository and OAI-PMH Harvester alone. The objective of OAI-PMH Static Repository and OAI-PMH Gateway is different and they are not useful in common cases, but only a rare one, so you can remove them, except if you really need them.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by MohamedCissoko** [comment]
Thank you for the reply, 
 I'll remove them.

Regards
